In [2]:
import numpy as np

In [ ]:
def adam_optimizer(alpha = 0.001, beta1 = 0.9, beta2 = 0.999, epsilon = 1e-8):
    m0 = 0
    v0 = 0
    m = np.array(m0)
    v = np.array(v0)
    converged = False
    i = 0
    while not converged:
        i+=1
        
    
    

Connected to pydev debugger (build 242.23726.102)


[<tf.Tensor: shape=(2, 4), dtype=float32, numpy=


array([[ 0.0000000e+00, -4.1458354e-04, -1.2156062e-02,  0.0000000e+00],
       [ 0.0000000e+00,  8.1599457e-05, -1.1105627e-02,  0.0000000e+00]],
      dtype=float32)>, <tf.Tensor: shape=(1, 4), dtype=float32, numpy=


array([[ 0.0000000e+00,  8.1599457e-05, -3.5984255e-02,  0.0000000e+00]],
      dtype=float32)>, <tf.Tensor: shape=(4, 1), dtype=float32, numpy=


array([[ 0.        ],
       [-0.00625188],
       [-0.05907966],
       [ 0.        ]], dtype=float32)>, <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.07623041]], dtype=float32)>]

Connected to pydev debugger (build 242.23726.102)


[[<tf.Tensor: shape=(2, 4), dtype=float32, numpy=


array([[ 0.0000000e+00, -4.1458354e-04, -1.2156062e-02,  0.0000000e+00],
       [ 0.0000000e+00,  8.1599457e-05, -1.1105627e-02,  0.0000000e+00]],
      dtype=float32)>, <tf.Tensor: shape=(1, 4), dtype=float32, numpy=


array([[ 0.0000000e+00,  8.1599457e-05, -3.5984255e-02,  0.0000000e+00]],
      dtype=float32)>, <tf.Tensor: shape=(4, 1), dtype=float32, numpy=


array([[ 0.        ],
       [-0.00625188],
       [-0.05907966],
       [ 0.        ]], dtype=float32)>, <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-0.07623041]], dtype=float32)>]]